language: generic

env:
  global:
    - CI="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x ./build-package.sh
  - ./build-package.sh

jobs:
  include:
    - stage: lint âœ¨
      script:
        - npm install
        - npm run lint

    - stage: release ðŸŽ‰
      if: branch = master
      script:
        - chmod u+x ./install-apm.sh
        - ./install-apm.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
