name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linux-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v1.0.0
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec

  linux-beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v1.0.0
      with:
        channel: 'beta'
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec

  macos-stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v1.0.0
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec

  macos-beta:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v1.0.0
      with:
        channel: 'beta'
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec

  windows-stable:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v1.0.0
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec

  windows-beta:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v1.0.0
      with:
        channel: 'beta'
    - name: Get Atom versions
      run: atom -v
    - name: Get APM versions
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec
  
  lint:
    needs: [linux-stable, linux-beta, macos-stable, macos-beta, windows-stable, windows-beta]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: NPM install
        run: npm ci 
      - name: Lint âœ¨
        run: npm run lint
